import type { Metadata } from "next";
import { Rubik, Roboto } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/layout/MainHeader";
import MainFooter from "@/components/layout/MainFooter";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik"
});
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto"
});

export const metadata: Metadata = {
  title: "Store - NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${roboto.variable}`}>
        <MainHeader />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
